main: com.riverbug07.linksplus.Main
name: LinksPlus
version: 1.0.1
author: Riverbug07
api-version: 1.15
commands:
  link:
    description: Open a website or URL!
    permission: linksplus.use
    usage: "Usage: /link <name> [player]"